apiVersion: apps/v1
kind: Deployment
metadata:
  name: rigistration
  namespace: dev-test
  labels:
    app: reg-appliction
    version: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reg-appliction
      version: alpha
  template:
    metadata:
      name: rigistration
      labels:
        app: reg-appliction
        version: alpha
    spec:
      containers:
      - name: rigistration
        image: 54.236.38.112:8083/registration-form:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: nexus-registration-form  
---

apiVersion: v1
kind: Service
metadata:
  name: rigistration-svc
  namespace: dev-test
  labels:
    app: reg-appliction
    version: alpha
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32566
  selector:
    app: reg-appliction
    version: alpha
    
    
   
 
  
